services:
  novnc:
    image: feiner/novnc-dotcursor:latest
    container_name: novnc
    network_mode: "host"
    environment:
      - VNC_SERVER=${VNC_ADDRESS}
    ports:
      - "6080:6080"
    restart: unless-stopped

  heizomat-mqtt:
    image: feiner/heizomat-mqtt:latest
    container_name: heizomat-mqtt
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=heizomat/hackschnitzel
      - SENSOR_BASENAME=hackschnitzel
      - PUBLISH_INTERVAL=600
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - VNC_ADDRESS=${VNC_ADDRESS}
      - VNC_PW=${VNC_PW}
      - DEBUG_OCR=false
    volumes:
      - ./debug_crops:/app/debug_crops
    restart: unless-stopped
