services:
  novnc:
    image: feiner/novnc-arm-dotcursor:latest
    container_name: novnc
    network_mode: "host"
    environment:
      - VNC_SERVER=192.168.0.248
    ports:
      - "6080:6080"
    restart: unless-stopped

  heizomat-mqtt:
    image: feiner/heizomat-mqtt:latest
    container_name: heizomat-mqtt
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
      - MQTT_BROKER_HOST=
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=heizomat/hackschnitzel
      - SENSOR_BASENAME=hackschnitzel
      - PUBLISH_INTERVAL=10
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - VNC_ADDRESS=
      - VNC_PW=
      - DEBUG_OCR=false
    volumes:
      - ./debug_crops:/app/debug_crops  # <--- Map the folder to your local drive
    restart: unless-stopped
